name: Sync Stories from Google Sheets

on:
  schedule:
    # Run daily at 9 AM UTC (10 AM CET, 11 AM CEST)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual trigger
    inputs:
      reason:
        description: 'Reason for manual sync'
        required: false
        default: 'Manual sync triggered'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt
      
      - name: Sync stories from Google Sheets
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: |
          python scripts/sync_stories.py
      
      - name: Validate generated data
        run: |
          python scripts/validate_data.py
      
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code _data/stories.yml || echo "changed=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push if changed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add _data/stories.yml
          git commit -m "Auto-sync: Update stories from Google Sheets [$(date +'%Y-%m-%d %H:%M UTC')]"
          git push
      
      - name: No changes detected
        if: steps.git-check.outputs.changed != 'true'
        run: |
          echo "No changes detected in stories.yml - nothing to commit"
      
      - name: Summary
        run: |
          echo "## Sync Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.git-check.outputs.changed }}" == "true" ]; then
            echo "✅ Stories updated and committed" >> $GITHUB_STEP_SUMMARY
          else
            echo "ℹ️ No changes detected" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Sync completed at: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
